CREATE TABLE tasks (
  ID SERIAL PRIMARY KEY,
  NAME TEXT NOT NULL,
  DESCRIPTION TEXT NOT NULL,
  PROJECT_ID INT NOT NULL,
  USER_ID INT NOT NULL
);

INSERT INTO tasks (NAME, DESCRIPTION, PROJECT_ID, USER_ID) VALUES ('Do server', 'Write web server on GO', 1, 1);
